### ISSUE TITLE
nvm is hanging when trying to forcefeed mkfs a 200k manifest (python)

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#84] opened 2018-12-04 00:26 UTC
was trying out the python 

```
cat ~/py2.7/config.json
{
    "Args":["test.py"],
    "Files":["test.py"],
    "Dirs":["usr"]
}
```

```
mkdir -p usr/
cp -R /usr/lib/python2.7/* usr/lib/python2.7/.
```

i traced it back to mkfs segfaulting on an invalid paren

```
eyberg@dungeon:~/tmp$ ./mkfs tempimage < dat1
parse error unknown property descriminator (
metadata (none)
Segmentation fault (core dumped)
```

so there are 2 issues here:

1) mkfs doesn't like the manifest being un-balanced - we should verify if that's the case and if it needs to be fixed nvm side do it there - if it needs to be fixed mkfs side do it there

2) we shouldn't sit and spin on a broken pipe - I believe a .wait() will catch this

**Comment by mkhon** [comment] 2019-01-22 14:48
1. Fixed in #428

2. I don't think there an issue with this

3. Fixed in #150 

4. The root cause is #nanos/427

I think this one can be closed now (initially was about big manifest and fixed in #150).

**Closed as completed** 2019-01-22 15:04 UTC
Labels: python
