### ISSUE TITLE
haproxy_2.3.0 local package getsockopt error

### ISSUE THREAD

**Issue by rrs45** [nanovms/ops#1121] opened 2021-07-25 03:26 UTC
Hi,

I am getting below with a local haproxy pkg built by copying libs from upstream docker image

_$ ops pkg load -l haproxy_2.3.0 --show-debug -n -p 8404,8083
warning: overwriting existing file /etc/resolv.conf hostpath old: /mnt/disks/disk1/.ops/local_packages/haproxy_2.3.0/sysroot/etc/resolv.conf new: /tmp/haproxy_temp875802455/resolv.conf
warning: overwriting existing file /proc/sys/kernel/hostname hostpath old: /mnt/disks/disk1/.ops/local_packages/haproxy_2.3.0/sysroot/proc/sys/kernel/hostname new: /tmp/haproxy_temp875802455/hostname
booting /mnt/disks/disk1/.ops/images/haproxy ...
You specified hardware acceleration, but it is not supported
Are you running inside a vm? If so disable accel with --accel=false

en1: assigned 10.0.2.15
[WARNING] 205/032001 (2) : config : 'stats' statement ignored for proxy 'stats' as it requires HTTP mode.
Note: setting global.maxconn to 32760.
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result FAILED
Total: 3 (2 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
Using epoll() as the polling mechanism.
getsockopt error: getsockopt unimplemented optname: fd 4, level 1, optname 30
getsockopt error: getsockopt unimplemented optname: fd 5, level 1, optname 30
en1: assigned FE80::CC5C:8BFF:FE8D:83E2`

 $ cat etc/haproxy/haproxy.cfg
global

defaults
    timeout connect  5000
    timeout client   50000
    timeout server   50000

frontend app
    mode http
    bind *:8083

listen stats
    bind *:8404
    stats enable
    stats uri /monitor
    stats refresh 5s `_

`.ops/local_packages/haproxy_2.3.0$ tree .
.
├── README.md
├── package.manifest
└── sysroot
    ├── etc
    │   ├── haproxy
    │   │   └── haproxy.cfg
    │   ├── passwd
    │   ├── resolv.conf
    │   └── ssl
    │       └── certs
    │           └── ca-certificates.crt
    ├── lib
    │   └── x86_64-linux-gnu
    │       ├── ld-2.28.so
    │       ├── ld-linux-x86-64.so.2 -> ld-2.28.so
    │       ├── libBrokenLocale-2.28.so
    │       ├── libBrokenLocale.so.1 -> libBrokenLocale-2.28.so
    │       ├── libSegFault.so
    │       ├── libanl-2.28.so
    │       ├── libanl.so.1 -> libanl-2.28.so
    │       ├── libaudit.so.1 -> libaudit.so.1.0.0
    │       ├── libaudit.so.1.0.0
    │       ├── libblkid.so.1 -> libblkid.so.1.1.0
    │       ├── libblkid.so.1.1.0
    │       ├── libbz2.so.1 -> libbz2.so.1.0.4
    │       ├── libbz2.so.1.0 -> libbz2.so.1.0.4
    │       ├── libbz2.so.1.0.4
    │       ├── libc-2.28.so
    │       ├── libc.so.6 -> libc-2.28.so
    │       ├── libcap-ng.so.0 -> libcap-ng.so.0.0.0
    │       ├── libcap-ng.so.0.0.0
    │       ├── libcom_err.so.2 -> libcom_err.so.2.1
    │       ├── libcom_err.so.2.1
    │       ├── libcrypt-2.28.so
    │       ├── libcrypt.so.1 -> libcrypt-2.28.so
    │       ├── libdl-2.28.so
    │       ├── libdl.so.2 -> libdl-2.28.so
    │       ├── libe2p.so.2 -> libe2p.so.2.3
    │       ├── libe2p.so.2.3
    │       ├── libext2fs.so.2 -> libext2fs.so.2.4
    │       ├── libext2fs.so.2.4
    │       ├── libfdisk.so.1 -> libfdisk.so.1.1.0
    │       ├── libfdisk.so.1.1.0
    │       ├── libgcc_s.so.1
    │       ├── libgcrypt.so.20 -> libgcrypt.so.20.2.4
    │       ├── libgcrypt.so.20.2.4
    │       ├── libgpg-error.so.0 -> libgpg-error.so.0.26.1
    │       ├── libgpg-error.so.0.26.1
    │       ├── liblzma.so.5 -> liblzma.so.5.2.4
    │       ├── liblzma.so.5.2.4
    │       ├── libm-2.28.so
    │       ├── libm.so.6 -> libm-2.28.so
    │       ├── libmemusage.so
    │       ├── libmount.so.1 -> libmount.so.1.1.0
    │       ├── libmount.so.1.1.0
    │       ├── libmvec-2.28.so
    │       ├── libmvec.so.1 -> libmvec-2.28.so
    │       ├── libncursesw.so.6 -> libncursesw.so.6.1
    │       ├── libncursesw.so.6.1
    │       ├── libnsl-2.28.so
    │       ├── libnsl.so.1 -> libnsl-2.28.so
    │       ├── libnss_compat-2.28.so
    │       ├── libnss_compat.so.2 -> libnss_compat-2.28.so
    │       ├── libnss_dns-2.28.so
    │       ├── libnss_dns.so.2 -> libnss_dns-2.28.so
    │       ├── libnss_files-2.28.so
    │       ├── libnss_files.so.2 -> libnss_files-2.28.so
    │       ├── libnss_hesiod-2.28.so
    │       ├── libnss_hesiod.so.2 -> libnss_hesiod-2.28.so
    │       ├── libnss_nis-2.28.so
    │       ├── libnss_nis.so.2 -> libnss_nis-2.28.so
    │       ├── libnss_nisplus-2.28.so
    │       ├── libnss_nisplus.so.2 -> libnss_nisplus-2.28.so
    │       ├── libpam.so.0 -> libpam.so.0.84.2
    │       ├── libpam.so.0.84.2
    │       ├── libpam_misc.so.0 -> libpam_misc.so.0.82.1
    │       ├── libpam_misc.so.0.82.1
    │       ├── libpamc.so.0 -> libpamc.so.0.82.1
    │       ├── libpamc.so.0.82.1
    │       ├── libpcprofile.so
    │       ├── libpcre.so.3 -> libpcre.so.3.13.3
    │       ├── libpcre.so.3.13.3
    │       ├── libpthread-2.28.so
    │       ├── libpthread.so.0 -> libpthread-2.28.so
    │       ├── libresolv-2.28.so
    │       ├── libresolv.so.2 -> libresolv-2.28.so
    │       ├── librt-2.28.so
    │       ├── librt.so.1 -> librt-2.28.so
    │       ├── libselinux.so.1
    │       ├── libsepol.so.1
    │       ├── libsmartcols.so.1 -> libsmartcols.so.1.1.0
    │       ├── libsmartcols.so.1.1.0
    │       ├── libss.so.2 -> libss.so.2.0
    │       ├── libss.so.2.0
    │       ├── libsystemd.so.0 -> libsystemd.so.0.25.0
    │       ├── libsystemd.so.0.25.0
    │       ├── libthread_db-1.0.so
    │       ├── libthread_db.so.1 -> libthread_db-1.0.so
    │       ├── libtinfo.so.6 -> libtinfo.so.6.1
    │       ├── libtinfo.so.6.1
    │       ├── libudev.so.1 -> libudev.so.1.6.13
    │       ├── libudev.so.1.6.13
    │       ├── libutil-2.28.so
    │       ├── libutil.so.1 -> libutil-2.28.so
    │       ├── libuuid.so.1 -> libuuid.so.1.3.0
    │       ├── libuuid.so.1.3.0
    │       ├── libz.so.1 -> libz.so.1.2.11
    │       └── libz.so.1.2.11
    ├── lib64
    │   └── ld-linux-x86-64.so.2
    ├── proc
    │   └── sys
    │       └── kernel
    │           └── hostname
    └── usr
        ├── lib
        │   └── x86_64-linux-gnu
        │       ├── libacl.so.1 -> libacl.so.1.1.2253
        │       ├── libacl.so.1.1.2253
        │       ├── libapt-pkg.so.5.0 -> libapt-pkg.so.5.0.2
        │       ├── libapt-pkg.so.5.0.2
        │       ├── libapt-private.so.0.0 -> libapt-private.so.0.0.0
        │       ├── libapt-private.so.0.0.0
        │       ├── libattr.so.1 -> libattr.so.1.1.2448
        │       ├── libattr.so.1.1.2448
        │       ├── libcrypto.so.1.1
        │       ├── libdb-5.3.so
        │       ├── libdebconfclient.so.0 -> libdebconfclient.so.0.0.0
        │       ├── libdebconfclient.so.0.0.0
        │       ├── libffi.so.6 -> libffi.so.6.0.4
        │       ├── libffi.so.6.0.4
        │       ├── libformw.so.6 -> libformw.so.6.1
        │       ├── libformw.so.6.1
        │       ├── libgmp.so.10 -> libgmp.so.10.3.2
        │       ├── libgmp.so.10.3.2
        │       ├── libgnutls.so.30 -> libgnutls.so.30.23.2
        │       ├── libgnutls.so.30.23.2
        │       ├── libhogweed.so.4 -> libhogweed.so.4.5
        │       ├── libhogweed.so.4.5
        │       ├── libidn2.so.0 -> libidn2.so.0.3.4
        │       ├── libidn2.so.0.3.4
        │       ├── liblua5.3-c++.so.0 -> liblua5.3-c++.so.0.0.0
        │       ├── liblua5.3-c++.so.0.0.0
        │       ├── liblua5.3.so.0 -> liblua5.3.so.0.0.0
        │       ├── liblua5.3.so.0.0.0
        │       ├── liblz4.so.1 -> liblz4.so.1.8.3
        │       ├── liblz4.so.1.8.3
        │       ├── libmenuw.so.6 -> libmenuw.so.6.1
        │       ├── libmenuw.so.6.1
        │       ├── libnettle.so.6 -> libnettle.so.6.5
        │       ├── libnettle.so.6.5
        │       ├── libp11-kit.so.0 -> libp11-kit.so.0.3.0
        │       ├── libp11-kit.so.0.3.0
        │       ├── libpanelw.so.6 -> libpanelw.so.6.1
        │       ├── libpanelw.so.6.1
        │       ├── libpcre2-8.so.0 -> libpcre2-8.so.0.7.1
        │       ├── libpcre2-8.so.0.7.1
        │       ├── libpcre2-posix.so.2 -> libpcre2-posix.so.2.0.1
        │       ├── libpcre2-posix.so.2.0.1
        │       ├── libpcreposix.so.3 -> libpcreposix.so.3.13.3
        │       ├── libpcreposix.so.3.13.3
        │       ├── libseccomp.so.2 -> libseccomp.so.2.3.3
        │       ├── libseccomp.so.2.3.3
        │       ├── libsemanage.so.1
        │       ├── libssl.so.1.1
        │       ├── libstdc++.so.6 -> libstdc++.so.6.0.25
        │       ├── libstdc++.so.6.0.25
        │       ├── libtasn1.so.6 -> libtasn1.so.6.5.5
        │       ├── libtasn1.so.6.5.5
        │       ├── libtic.so.6 -> libtic.so.6.1
        │       ├── libtic.so.6.1
        │       ├── libunistring.so.2 -> libunistring.so.2.1.0
        │       ├── libunistring.so.2.1.0
        │       ├── libzstd.so.1 -> libzstd.so.1.3.8
        │       └── libzstd.so.1.3.8
        ├── local
        │   └── sbin
        │       └── haproxy
        └── sbin
            └── haproxy`

`$ ops profile
Ops version: 0.1.24
Nanos version: 0.1.35
Qemu version: 3.1.0
Arch: linux
Virtualized: true`

**Comment by eyberg** [comment] 2021-07-25 17:34
this is just a warning right?

I think it is because we are missing SO_ACCEPTCONN but that looks like it should be straight-forward to add

**Comment by rrs45** [comment] 2021-07-25 21:13
Yes but i need to test further. Is any documentation on what socket options are supported? 

Also, latest haproxy requires net.ipv4.ip_unprivileged_port_start=0 sysctl, is this supported?

Whats the release cadence for nanos? When is the next stable release scheduled?

Thanks!

**Comment by eyberg** [comment] 2021-07-25 22:55
I don't know offhand if this is an authoritative list or not but https://github.com/nanovms/nanos/blob/722166cae2cf2474f367d69416ed6f2cb1f63a4e/src/unix/system_structs.h#L729 has some defined

ip_unpirvileged_port shoudn't matter since we don't deal with users, you can listen on whatever port you want

we don't have a set release cadence defined; right now it's mostly whenever we feel that certain features warrant a new one or there is a chunk of code that end-customers are waiting on and not wanting to use nightly

**Comment by rrs45** [comment] 2021-07-25 23:11
Sounds good. Would be a good practice to have a release cadence with stricter & well defined testing criteria, just a thought. 

I see that some of socket options mentioned below are missing, are these not applicable?

SO_ACCEPTCONN
SO_BROADCAST
SO_DEBUG
SO_DONTROUTE
SO_ERROR
SO_KEEPALIVE
SO_LINGER
SO_OOBINLINE
SO_RCVBUF
SO_RCVLOWAT
SO_RCVTIMEO
SO_REUSEADDR
SO_SNDBUF
SO_SNDLOWAT
SO_SNDTIMEO
SO_TYPE

**Comment by eyberg** [comment] 2021-07-25 23:20
some of these we do have and in fact things like SO_DEBUG and SO_LINGER are in that list I pasted, also some of these can be listed elsewhere

as for tests we do have ci setup - both on what can be ran in circleci and then also a jenkins for kvm/performance tests

**Comment by eyberg** [comment] 2021-07-26 19:39
https://github.com/nanovms/nanos/pull/1548

**Comment by francescolavra** [comment] 2021-07-29 13:58
The issue is now fixed in Nanos nightly build.

**Closed by francescolavra** 2021-07-29 13:58 UTC
Labels: networking

**Comment by rrs45** [comment] 2021-07-29 16:31
Awesome!
